version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gocognit
    - gocyclo
    - nestif
    - revive
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - wsl
    - ireturn      # Interface return types (common in frameworks)
    - lll          # Line length (some documentation strings are long)
    - maintidx     # Maintainability index (would require major refactoring)
    - nlreturn     # Newline before return (style preference)
    - noinlineerr  # Inline error handling (minor style issue)
    - wsl_v5       # Whitespace style (cosmetic)

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
