---
name: Changelog
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@b92245bb38f21aef0dd1abdc1ed431e9951e71fb # main
